### PR TITLE
Refined tracks

### PR DESCRIPTION
**Pull request by MichaelGoodale**
This PR adds an option to save formant tracks rather than formant points when using the refined formant tracks.

### CODE REVIEW

**Comment by MichaelGoodale** [comment]
this will fix #218

**Comment by MichaelGoodale** [comment]
Hmm, there seems to be some sort of issue calling `analyze_segments` within Celery. It worked previously using `formants.py` from the SPADE repo but doesn't seem to work with ISCAN. Have you encountered this before @mmcauliffe  ?

```
ps-worker           | [2019-06-12 17:51:56,454: WARNING/ForkPoolWorker-2] output_columns:
ps-worker           | [2019-06-12 17:51:56,454: WARNING/ForkPoolWorker-2] ['F1', 'F2', 'F3', 'B1', 'B2', 'B3', 'A1', 'A2', 'A3', 'Ax', 'A1A2diff', 'A2A3diff']
ps-worker           | [2019-06-12 17:51:56,456: WARNING/ForkPoolWorker-2] michael ae: 1 of 8: 4 tokens
ps-worker           | [2019-06-12 17:51:56,476: WARNING/ForkPoolWorker-2] Traceback (most recent call last):
ps-worker           |   File "/site/proj/ISCAN/iscan/models.py", line 1011, in run_enrichment
ps-worker           |     output_tracks=output_tracks
ps-worker           |   File "/site/proj/PolyglotDB/polyglotdb/acoustics/formants/refined.py", line 119, in analyze_formant_points_refinement
ps-worker           |     multiprocessing=multiprocessing)  # Analyze the phone
ps-worker           |   File "/site/env/lib/python3.6/site-packages/conch/main.py", line 200, in analyze_segments
ps-worker           |     call_back, stop_check)
ps-worker           |   File "/site/env/lib/python3.6/site-packages/conch/multiprocessing.py", line 161, in generate_cache
ps-worker           |     manager = Manager()
ps-worker           |   File "/usr/lib/python3.6/multiprocessing/context.py", line 56, in Manager
ps-worker           |     m.start()
ps-worker           |   File "/usr/lib/python3.6/multiprocessing/managers.py", line 513, in start
ps-worker           |     self._process.start()
ps-worker           |   File "/usr/lib/python3.6/multiprocessing/process.py", line 103, in start
ps-worker           |     'daemonic processes are not allowed to have children'
ps-worker           | AssertionError: daemonic processes are not allowed to have children
ps-worker           | [2019-06-12 17:51:56,489: INFO/ForkPoolWorker-2] Task iscan.tasks.run_enrichment_task[e890462b-fe77-4038-9c17-11589aeb36d8] succeeded in 4.214987319999636s: None
ps-app              | [12/Jun/2019 17:52:03

```

**Comment by MichaelGoodale** [comment]
nvm, fixed it in PolyglotDB

**Comment by msonderegger** [comment]
Excellent! @mmcauliffe ?

**Pull request merged**
